# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            mtheunissen82
tagline:          'Extension for my brain'
description:      '<b>/dev/null</b> for stuff i think i need to remember... hardly a blog...'
url:              https://github.com/algolia/algoliasearch-jekyll-hyde
baseurl:          '' 
# Travis will install Bundler dependencies in ./vendor, so we need to exclude it
# otherwise Jekyll will try to build it (and fail)
exclude:          [vendor]

author:
  name:           'Algolia'
  url:            https://www.algolia.com/
# Thanks to @mdo for the original theme
# author:
#   name:           'Mark Otto'
#   url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
    repo:         https://github.com/algolia/algoliasearch-jekyll-hyde

# Algolia
gems:
  - algoliasearch-jekyll

algolia:
  application_id: 'latency'
  index_name: 'jekyll'
  read_only_api_key: '6be0576ff61c053d5f9a3225e2a90f76'
  excluded_files:
    - 404.html
    - index.html
